version: "2"

services:
  voting-app:
    build: ./voting-app/.
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: private-repo.microsoft.com/mssql-private-preview/mssql-server:latest
    environment:
      SA_PASSWORD: NeverCommitPasswordsToSourceExceptForDemos
      ACCEPT_EULA: Y
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
